// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umlqofhdkmsusxvsubqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbHFvZmhka21zdXN4dnN1YnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NTAwNzQsImV4cCI6MjA4ODUyNjA3NH0.MI8McD-VF3I-9Z81YARbKNFXDrRgW_jGbkCnFIsH-uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});